server {
    listen 80;

    # Serve React Frontend
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # The API Rewrite Magic
    location /api/ {

        proxy_pass http://bs-server:5000/; 
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}