services:
  bs-backend:
    container_name: bs-backend
    build: .
    image: bs-backend
    env_file:
      - .env
    ports:
      - "5000:3000"
    depends_on:
      - db
  
  db:
    image: postgres:latest 
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"